config/routes.rb
Rails.application.routes.draw do
  get 'recipe_foods/new'
  resources :foods
  resources :shopping_list, only: [:show]
  post '/shopping_list/:recipe_id', to: 'shopping_list#show', as: 'shopping_show'
  devise_for :users

  resources :recipes, only: [:index, :show, :new, :create, :destroy, :put ] do
    resources :recipe_foods, path: 'food', only: [:destroy, :new, :create]
  end

  resources :inventories, except: :update do
    resources :inventory_foods, except: :update
  end

  match 'recipes/:recipe_id' => 'recipes#toogle_public', as: :toogle_public, via: :patch
  match 'public_recipes' => 'recipes#public_recipes', as: :public_recipes, via: :get

  root 'recipes#public_recipes'
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user

  has_many :inventory_foods
  has_many :foods, through: :inventory_foods

  validates :name, presence: true
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  def index
    @user = current_user
    @inventories = Inventory.where(user_id: current_user.id)
  end

  def new
    @inventory = Inventory.new
  end

  def show
    @inventory = current_user.inventories.find(params[:id])
  end

  def create
    @user = current_user
    @inventory = Inventory.new(inventory_params)
    @inventory.user = @user

    respond_to do |format|
      if @inventory.save
        format.html { redirect_to inventories_path, notice: 'inventory was successfully created.' }
        format.json { render :index, status: :created, location: @inventory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inventory.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    @inventory.destroy

    respond_to do |format|
      format.html { redirect_to inventories_path, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def inventory_params
    params.require(:inventory).permit(:name, :description, :user_id)
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/index.html.erb
<div class="d-flex flex-column mb-2 align-items-center">
  <div class="d-flex">
    <h1 class="m-3 text-secondary"><%= @user.name %>'s Inventories</h1>
  </div>
  <%= link_to "New inventory", new_inventory_path, class: "btn btn-outline-primary align-self-center my-3" %>
  <% if @inventories.empty? %>
    <p class="mt-5 border border-warning font-weight-bold text-warning">
      <span class="p-3">You don't have any inventories</span>
    </p>
  <% else %>
    <%= render partial: "shared/inventory", collection: @inventories %>
  <% end %>
</div>

app/views/inventories/new.html.erb
<div class="d-flex flex-column mb-2 align-items-center">
  <h1 class="m-3 text-secondary">New Inventory</h1>
  <%= bootstrap_form_with(model: Inventory, class: "contents") do |form| %>
    <% if @inventory.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2 class="text-danger"><%= pluralize(@inventory.errors.count, "error") %> prohibited this inventory from being saved:</h2>
        <ul>
          <% @inventory.errors.each do |error| %>
            <li class="text-danger"><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= bootstrap_form_for(@inventory) do |f| %>
      <%= f.text_field :name, wrapper: { class: 'text-secondary' } %>
      <%= f.text_area :description, wrapper: { class: 'text-secondary' } %>
      <div class="my-3 text-center">
        <%= f.submit "Add inventory", class: "btn btn-primary" %>
      </div>
    <% end %>
  <% end %>
  <div class="mt-3">
    <%= link_to 'Back to inventories', inventories_path, class: "rounded-lg py-3 bg-gray-100 inline-block font-medium text-secondary" %>
  </div>
</div>

app/views/inventories/show.html.erb
<div class="d-flex flex-column mb-2 align-items-center">
  <div class="d-flex mb-2">
    <h1 class="mx-3 text-secondary"><%= @inventory.name %></h1>
  </div>
  <%= link_to 'Add Food', new_inventory_inventory_food_path(@inventory), class: "btn btn-outline-primary align-self-center my-3" %>
  <table class="table table-light table-striped w-50 mt-3">
    <thead>
    <tr>
      <th scope="col" class="text-secondary">Food</th>
      <th scope="col" class="text-secondary">Quantity</th>
      <th scope="col" class="text-secondary">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @inventory.inventory_foods.includes([:food]).each do |food| %>
      <tr>
        <td class="text-secondary"><%= food.food.name %></td>
        <td class="text-secondary"><%= "#{food.quantity} #{food.food.measurement_unit}" %></td>
        <td class="text-secondary">
          <%= button_to "Remove", inventory_inventory_food_path(@inventory, food), method: :delete, class: "btn btn-outline-danger" %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>