config/routes.rb
Rails.application.routes.draw do
  get 'recipe_foods/new'
  resources :foods
  resources :shopping_list, only: [:show]
  post '/shopping_list/:recipe_id', to: 'shopping_list#show', as: 'shopping_show'
  devise_for :users

  resources :recipes, only: [:index, :show, :new, :create, :destroy, :put ] do
    resources :recipe_foods, path: 'food', only: [:destroy, :new, :create]
  end

  resources :inventories, except: :update do
    resources :inventory_foods, except: :update
  end

  match 'recipes/:recipe_id' => 'recipes#toogle_public', as: :toogle_public, via: :patch
  match 'public_recipes' => 'recipes#public_recipes', as: :public_recipes, via: :get

  root 'recipes#public_recipes'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :public, inclusion: { in: [true, false] }
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @current_user = current_user
    if @current_user.nil?
      redirect_to user_session_path, flash: { alert: 'You must be signed in to continue.' }
    else
      @recipes = @current_user.recipes
    end
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find_by_id(params[:id])
    @recipe_foods = @recipe&.recipe_foods
    @recipe = 'No recipes' if @recipe.nil?
    @current_user = current_user
    @inventories = current_user&.inventories
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @foods = Food.all
    @recipe.recipe_foods.build
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params.merge(user: current_user))

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe = Recipe.find_by_id(params[:id])
    return unless @recipe.user == current_user

    if @recipe.destroy
      respond_to do |format|
        format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to recipes_url, notice: 'Recipe was not destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def toogle_public
    @recipe = set_recipe
    @recipe.public = !@recipe.public
    text = 'private'
    text = 'public' if @recipe.public
    if @recipe.save
      flash[:success] = "#{@recipe.name} is now #{text}!"
    else
      flash[:fail] = @recipe.public
    end
    redirect_to recipe_path(@recipe.id)
  end

  def public_recipes
    @recipes = Recipe.where(public: true)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, class: "contents") do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p>
    <strong>Preparationtime:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p>
    <strong>Cookingtime:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>

</div

app/views/recipes/_recipe_food.html.erb
<tr>
  <td> <%= recipe_food.food.name %></td>
  <td><%= recipe_food.quantity %> <%= recipe_food.food.measurement_unit %></td>
  <td><%= recipe_food.food.price * recipe_food.quantity %></td>
  <% if recipe_food.recipe.user == current_user %>
    <td>
        <%= button_to "Remove", recipe_recipe_food_path(recipe_food.recipe_id, recipe_food.id), method: :delete, class: "btn btn-outline-dark align-self-center"%>
    </td>
  <% end %>
</tr>

app/views/recipes/create.html.erb
<h1>Recipes#create,</h1>
<p>Find me in app/views/recipes/create,.html.erb</p>

app/views/recipes/destroy.html.erb
<h1>Recipes#destroy</h1>
<p>Find me in app/views/recipes/destroy.html.erb</p>

app/views/recipes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing recipe</h1>

  <%= render "form", recipe: @recipe %>

  <%= link_to "Show this recipe", @recipe, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to recipes", recipes_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/recipes/index.html.erb
<div class="d-flex flex-column mb-2 align-items-center">
  <div class="d-flex">
    <h1 class="m-3 text-secondary"> <%= @current_user.name %>'s Recipes</h1>
  </div>
  <% if user_signed_in? %>
    <%= link_to "New Recipe", new_recipe_path, class: "btn btn-outline-primary align-self-center my-3" %>
  <% end %>
  <% if @recipes.empty? %>
    <p class="border p-7 border-yellow-400 bg-yellow-200 font-medium">You don't have any recipes.</p>
  <% else %>
    <%= render partial: "shared/recipe", collection: @recipes %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="w-full">
  <h1 class="font-bold text-4xl">New Recipe</h1>
  <div class="mt-14">
    <%= form_with model: @recipe, url: recipes_path, local: true, html: {"data-turbo": "false"} do |form| %>
      <% if @recipe.errors.any? %>
        <div class="border px-7 py-3 mb-4 border-red-400 bg-red-200 font-medium">
          <% @recipe.errors.full_messages.each do |msg| %>
            <p><%= msg %></p>
          <% end %>
        </div>
      <% end %>
      <div class="border p-7 flex flex-col gap-7">
        <div>
          <%= form.label :name, class: 'font-medium block mb-2' %>
          <%= form.text_field :name, class: 'border rounded' %>
        </div>
        <div>
          <%= form.label :preparation_time, class: 'font-medium block mb-2' %>
          <%= form.number_field :preparation_time, class: 'border rounded', placeholder: 'In minutes' %>
        </div>
        <div>
          <%= form.label :cooking_time, class: 'font-medium block mb-2' %>
          <%= form.number_field :cooking_time, class: 'border rounded', placeholder: 'In minutes' %>
        </div>
        <div>
          <%= form.label :description, class: 'font-medium block mb-2' %>
          <%= form.text_area :description, class: 'border rounded' %>
        </div>
        <div>
          <%= form.label :public, class: 'form-check-label'%>
          <%= form.check_box :public , class: 'form-check-input'%>
        </div>
        <%= form.submit "Submit", class: 'text-sm px-4 py-2 bg-transparent hover:bg-teal-500 text-teal-700 max-w-fit font-semibold hover:text-white border border-teal-500 hover:border-transparent rounded' %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/public_recipes.html.erb
<div class="d-flex flex-column mb-2 align-items-center">
  <h1 class="my-3 text-center text-secondary">All Recipes</h1>
  <% if @recipes.empty? %>
    <p class="text-center text-warning">No public recipes.</p>
  <% else %>
    <%= render partial: "shared/public_recipe", collection: @recipes %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<h1 class="text-center"><%= @recipe.name %></h1>
<div class="card w-75 container">
  <div class="card-body row align-items-between">
    <div class="col col-md-6 ms-3">
      <h4 class="fw-bold my-1">Preparation Time: <%= @recipe.preparation_time / 60 %>
        hours <%= @recipe.preparation_time % 60 %> minutes</h4>
      <h4 class="fw-bold my-4">Cooking Time: <%= @recipe.cooking_time / 60 %> hours <%= @recipe.cooking_time % 60 %>
        minutes</h4>
    </div>
    <div class="col col-md-4 ms-auto">
      <div class="d-flex justify-content-around form-check form-switch">
        <p class="form-check-label" for="flexSwitchCheckChecked">Private</p>
        <input class="form-check-input ms-1" type="checkbox" role="switch" id="flexSwitchCheckChecked" data-size="lg" checked>
        <label class="form-check-label" for="flexSwitchCheckChecked">Public</label>
      </div>
      <p class="ms-5 fs-12 text-danger">Update CRUD is not implemented</p>
    </div>
  </div>
  <div class="row card-body">
    <div class="card-body col col-md-12">
      <h4 class="fw-bold my-1">Description</h4>
      <p class="fs-6">
        <%= @recipe.description %>
    </div>
    <div class="row">
      <div class="col col-md-6">
        <% if @inventories.length > 0 %>
          <button type="button" class="btn btn-outline-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
            Generate shopping list
          </button>
        <% end %>

        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">Generate shopping list</h3>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <h5>Choose an inventory to use</h5>
                <%= bootstrap_form_with url: shopping_list_path(params[:id]), scope: :inventory_food do |f| %>
                  <% inventory_array = @inventories.map { |f| [f.name, f.id] } %>
                  <%= f.select(:inventory_id, options_for_select(inventory_array), class: "select-tag") %>
                  <div class="my-3 text-center">
                    <%= f.submit "Generate", class: "btn btn-primary" %>
                  </div>

                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                  </div>
                  </div>
                  </div>
                  </div>

                <% end %>

                <!-- Modal -->
                <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h3 class="modal-title" id="exampleModalLabel">Generate shopping list</h3>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        <h5>Choose an inventory to use</h5>
                        <%= bootstrap_form_with url: shopping_list_path(params[:id]), scope: :inventory_food do |f| %>
                          <% inventory_array = @inventories.map { |f| [f.name, f.id] } %>
                          <%= f.select(:inventory_id, options_for_select(inventory_array), class: "select-tag") %>
                          <div class="my-3 text-center">
                            <%= f.submit "Generate", class: "btn btn-primary" %>
                          </div>
                        <% end %>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                      </div>
                    </div>
                  </div>
                </div>
                </div>
      <div class="col col-md-6 ms-auto">
        <% if @recipe.user == @current_user %>
          <%= link_to "Add Ingredients", new_recipe_recipe_food_path(@recipe.id), class: "btn btn-outline-dark" %>
        <% end %>
      </div>
      <table class="table">
        <thead>
        <tr>
          <th scope="col">Food</th>
          <th scope="col">Quantity</th>
          <th scope="col">Value</th>
          <% if @recipe.user == current_user %>
            <th scope="col">Action</th>
          <% end %>
        </tr>
        </thead>
        <tbody><%= render partial: "recipe_food", collection: @recipe_foods %>
      </table>
    </div>
  </div>
</div>