config/routes.rb
Rails.application.routes.draw do
  get 'recipe_foods/new'
  resources :foods
  resources :shopping_list, only: [:show]
  post '/shopping_list/:recipe_id', to: 'shopping_list#show', as: 'shopping_show'
  devise_for :users

  resources :recipes, only: [:index, :show, :new, :create, :destroy, :put ] do
    resources :recipe_foods, path: 'food', only: [:destroy, :new, :create]
  end

  resources :inventories, except: :update do
    resources :inventory_foods, except: :update
  end

  match 'recipes/:recipe_id' => 'recipes#toogle_public', as: :toogle_public, via: :patch
  match 'public_recipes' => 'recipes#public_recipes', as: :public_recipes, via: :get

  root 'recipes#public_recipes'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, Recipe, public: true

    return unless user.present? # additional permissions for logged in users (they can read their own posts)

    can :manage, Recipe, user_id: user.id
    can :manage, Food, user_id: user.id
    can :manage, Inventory, user_id: user.id
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods
  has_many :inventories, through: :inventory_foods
  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  belongs_to :user

  has_many :inventory_foods
  has_many :foods, through: :inventory_foods

  validates :name, presence: true
end

app/models/inventory_food.rb
class InventoryFood < ApplicationRecord
  belongs_to :inventory
  belongs_to :food
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :public, inclusion: { in: [true, false] }
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :inventories, dependent: :destroy
  has_many :foods, dependent: :destroy
  has_many :recipes, dependent: :destroy

  validates :name, presence: true, length: { maximum: 100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @user = current_user
    @foods = @user.foods
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @user = current_user
    @food = Food.new(food_params)
    @food.user = @user

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully created.' }
        format.json { render :index, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_path, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]

  # GET /recipes or /recipes.json
  def index
    @current_user = current_user
    if @current_user.nil?
      redirect_to user_session_path, flash: { alert: 'You must be signed in to continue.' }
    else
      @recipes = @current_user.recipes
    end
  end

  # GET /recipes/1 or /recipes/1.json
  def show
    @recipe = Recipe.find_by_id(params[:id])
    @recipe_foods = @recipe&.recipe_foods
    @recipe = 'No recipes' if @recipe.nil?
    @current_user = current_user
    @inventories = current_user&.inventories
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
    @foods = Food.all
    @recipe.recipe_foods.build
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params.merge(user: current_user))

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe = Recipe.find_by_id(params[:id])
    return unless @recipe.user == current_user

    if @recipe.destroy
      respond_to do |format|
        format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to recipes_url, notice: 'Recipe was not destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def toogle_public
    @recipe = set_recipe
    @recipe.public = !@recipe.public
    text = 'private'
    text = 'public' if @recipe.public
    if @recipe.save
      flash[:success] = "#{@recipe.name} is now #{text}!"
    else
      flash[:fail] = @recipe.public
    end
    redirect_to recipe_path(@recipe.id)
  end

  def public_recipes
    @recipes = Recipe.where(public: true)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/helpers/inventory_foods_helper.rb
module InventoryFoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipeApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</head>

<body>
<%= render "shared/navbar" %>
<div class="container">
  <% render 'shared/alerts' %>
  <%= yield %>
</div>
</body>
</html>

app/views/shared/_alerts.html.erb
<div class="alert alert-success" role="alert"> <%= notice %> </div> 

app/views/shared/_inventory.html.erb
<div class="card w-75 my-2">
  <div class="card-body row">
    <div class="col col-md-4 ms-3  align-self-center">
      <h2 class="fw-bold"><%= link_to inventory.name, inventory_path(inventory.id), class: "card-title text-secondary text-decoration-none" %></h2>
      <%= button_to "Remove", inventory_path(inventory.id), method: :delete, class: "btn btn-outline-primary mt-2" %>
    </div>
    <div class="col col-md-6">
      <p class="fs-5 text-secondary"><%= inventory.description %></p>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
  <div class="container-fluid">
    <%= link_to "Recipe Book", root_path, class: "navbar-brand px-2" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Food List', foods_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Public Recipes', root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'My Recipes', recipes_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Inventories', inventories_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Shopping List', root_path, class: "nav-link" %>
          </li>
          </ul>
          <ul class="nav justify-content-end">
            <li class="nav-item">
              <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: "btn btn-outline-light" %>
            </li>
          </ul>
        <% else %>
          <ul class="nav justify-content-end">
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: "nav-link text-light" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link text-light" %>
            </li>
          </ul>
        <% end %>
        </div>
  </div>
</nav>

app/views/shared/_public_recipe.html.erb
<div class="card w-75 my-2">
  <div class="card-body row align-items-between">
    <div class="col col-md-6 ms-3">
      <h2 class="fw-bold"><%= link_to public_recipe.name, recipe_path(public_recipe.id), class: "card-title text-secondary text-decoration-none" %></h2>
      <p class="card-text fw-light fst-italic text-info"> written by: <%= public_recipe.user.name %> </p>
    </div>
    <div class="col col-md-4 ms-auto">
      <p class="fs-4 fw-bold text-secondary">Total food items: 0 </p>
      <p class="fs-4 fw-bold text-secondary">Total food price: 0 </p>
    </div>
  </div>
</div>

app/views/shared/_recipe.html.erb
<div class="card w-75 my-2">
  <div class="card-body row">
    <div class="col col-md-4 ms-3  align-self-center">
      <h2 class="fw-bold"><%= link_to recipe.name, recipe_path(recipe.id), class: "card-title text-secondary text-decoration-none" %></h2>
      <% if recipe.public %>
      <p class="text-info">Public</p>
      <% else %>
      <p class="text-info">Private</p>
      <% end %>
      <%= button_to "REMOVE", recipe_path(recipe.id), method: :delete, class: "btn btn-outline-danger" %>
    </div>
    <div class="col col-md-6">
      <p class="fs-5 text-secondary"><%= recipe.description %></p>
    </div>
  </div>
</div>