config/routes.rb
Rails.application.routes.draw do
  get 'recipe_foods/new'
  resources :foods
  resources :shopping_list, only: [:show]
  post '/shopping_list/:recipe_id', to: 'shopping_list#show', as: 'shopping_show'
  devise_for :users

  resources :recipes, only: [:index, :show, :new, :create, :destroy, :put ] do
    resources :recipe_foods, path: 'food', only: [:destroy, :new, :create]
  end

  resources :inventories, except: :update do
    resources :inventory_foods, except: :update
  end

  match 'recipes/:recipe_id' => 'recipes#toogle_public', as: :toogle_public, via: :patch
  match 'public_recipes' => 'recipes#public_recipes', as: :public_recipes, via: :get

  root 'recipes#public_recipes'
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods
  has_many :inventories, through: :inventory_foods
  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  has_many :recipe_foods
  has_many :recipes, through: :recipe_foods
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]

  # GET /foods or /foods.json
  def index
    @user = current_user
    @foods = @user.foods
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @user = current_user
    @food = Food.new(food_params)
    @food.user = @user

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food was successfully created.' }
        format.json { render :index, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_path, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price)
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <% if action_name != "show" %>
    <%= link_to "Show this food", food, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this food', edit_food_path(food), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food, class: "contents") do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>
      <ul>
        <% food.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= bootstrap_form_for(@food) do |f| %>
    <%= f.text_field :name, wrapper: { class: 'text-secondary' } %>
    <%= f.text_field :measurement_unit, wrapper: { class: 'text-secondary' } %>
    <%= f.text_field :price, wrapper: { class: 'text-secondary' } %>
    <div class="my-3 text-center">
      <%= f.submit "Add food", class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/foods/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing food</h1>

  <%= render "form", food: @food %>

  <%= link_to "Show this food", @food, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to foods", foods_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/foods/index.html.erb
<div class="d-flex flex-column mb-2 align-items-center">
<h1 class="mx-3 text-secondary">Food List</h1>
<%= link_to "Add food", new_food_path, class: "btn btn-outline-primary align-self-center my-3" %>

<table class="table table-light table-striped w-50 mt-3">
  <thead>
    <tr>
      <th scope="col" class="text-secondary">Food</th>
      <th scope="col" class="text-secondary">measurement unit</th>
      <th scope="col" class="text-secondary">Unit Price</th>
      <th scope="col" class="text-secondary">Actions</th>
    </tr>
  </thead>
  <tbody>
      <% @foods.each do |food| %>
      <tr>
        <td class="text-secondary"><%= food.name %></td>
        <td class="text-secondary"><%= food.measurement_unit %></td>
        <td class="text-secondary"><%= food.price %></td>
        <td class="text-secondary">
          <%= button_to "Delete", food_path(food.id), method: :delete, class: "btn btn-outline-danger" %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>
</div>

app/views/foods/new.html.erb
<div class="d-flex flex-column mb-2 align-items-center">
  <h1 class="m-3 text-secondary">New food</h1>

  <%= render "form", food: @food %>

  <%= link_to 'Back to foods', foods_path, class: "rounded-lg py-3 bg-gray-100 inline-block font-medium text-secondary" %>
</div>

app/views/foods/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @food %>

    <%= link_to 'Edit this food', edit_food_path(@food), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this food', food_path(@food), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to foods', foods_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>